// web-old/src/lib/components/FeatureCard.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';

	interface Props {
		icon: string;
		title: string;
		description: string;
	}

	const { icon, title, description }: Props = $props();
</script>

<div
	class="group rounded-2xl border border-separator-secondary bg-fill-tertiary p-6 transition-all duration-300 hover:border-separator-primary hover:shadow-lg"
>
	<div
		class="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-accent-primary transition-transform duration-300 group-hover:scale-110"
	>
		<Icon {icon} class="h-6 w-6 text-background-primary" />
	</div>
	<h3 class="mb-2 font-display text-lg font-bold text-label-primary">{title}</h3>
	<p class="text-sm leading-relaxed text-label-secondary">{description}</p>
</div>

// web/src/components/FeatureCard.tsx
import { Icon } from '@iconify/react';

interface Props {
  icon: string;
  title: string;
  description: string;
}

export default function FeatureCard({ icon, title, description }: Props) {
  return (
    <div className="group rounded-2xl border border-separator-secondary bg-fill-tertiary p-6 transition-all duration-300 hover:border-separator-primary hover:shadow-lg">
      <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-accent-primary transition-transform duration-300 group-hover:scale-110">
        <Icon icon={icon} className="h-6 w-6 text-background-primary" />
      </div>
      <h3 className="mb-2 font-display text-lg font-bold text-label-primary">{title}</h3>
      <p className="text-sm leading-relaxed text-label-secondary">{description}</p>
    </div>
  );
}
